### ISSUE TITLE
您好,MVPArms 正常收集优秀的 MVPArms 学习项目

### ISSUE THREAD

**Issue by JessYanCoding** [DesignQu/Project-Frame-MVP#1]
觉得您的项目挺不错的,希望您将此项目地址 **Pull Request** 到 https://github.com/JessYanCoding/MVPArms/blob/master/CONTRIBUTING_APP.md ,这样您也成为了 **MVPArms** 贡献者中的一员,还可以为此项目带来流量,**MVPArms** 还将继续成长变的更加强大,希望您一直坚持维护此项目✊

**Comment by RockyQu** [comment]
@JessYanCoding 怎么加？这是个demo，修改加了些自己的东西，也不能算是项目吧

**Comment by DesignQu** [comment]
@JessYanCoding 正在用在项目里，但是目前的项目是给政府做的一个在政务内网用的，不是对外公开的

**Comment by DesignQu** [comment]
@JessYanCoding 正在用在项目里，但是目前的项目是给政府做的一个在政务内网用的，不是对外公开的，是一个挺大的项目，有近百个模块

**Comment by JessYanCoding** [comment]
嗯,我看了你的项目,的确加了很多东西,虽然是 **Demo** ,但是却可以给别人在优化框架上一些思路,具体步骤是,先 **Fork MVPArms** ,在 **Fork** 的仓库里,修改 **CONTRIBUTING_APP.md ** 按格式添加自己的项目地址到里面,然后在 **MVPArms Github** 主页上,点击 **New pull request** ,具体可以百度,如果你觉得麻烦我可以帮你添加上去,我只是想给大家参与 **MVPArms** 代码贡献的机会

**Comment by DesignQu** [comment]
@JessYanCoding 我先自己弄下，不懂在问你

**Comment by RockyQu** [comment]
@JessYanCoding 我刚好像是提交了，你看你那能不能看到

**Comment by JessYanCoding** [comment]
OK,看到了,感谢支持,希望你一直维护下去,共同进步👍

**Comment by RockyQu** [comment]
@JessYanCoding 谢谢
