### ISSUE TITLE
数据库导入问题 谢谢

### ISSUE THREAD

**Issue by kandra777** [DesignQu/Project-Frame-MVP#2]
没有看到作者在哪里通过AppComponent注入了数据库啊?只看到了一个DB.Module的提供的类 请指教一下是在哪里注入的?

**Comment by RockyQu** [comment]
暂时还没用到注入，因为这个数据库有些文件是动态生成的，不能完全封装到Common里，框架的AppComponent是在框架里完成注入的，除非选用其他的数据库
