### ISSUE TITLE
Https 你是怎么绑定证书？

### ISSUE THREAD

**Issue by Puppy-Love** [DesignQu/Project-Frame-MVP#3]
看你代码好像没做这个操作啊

**Comment by RockyQu** [comment]
Https吗？确实没写支持Https啊，在哪看的？

**Comment by RockyQu** [comment]
这个框架没记得写过支持Https的啊。。。

**Comment by Puppy-Love** [comment]
String PHP = "https://api.shaimobao.com/"; 你定义的请求 不也是https啊，

**Comment by RockyQu** [comment]
这个是我项目的，这个https不需要绑定证书

**Comment by Puppy-Love** [comment]
恩 好吧，知道了，MVPArms 也是不能支持https，除非不用gradle导入，自己导入库 改源代码

**Comment by Puppy-Love** [comment]
你这个框架如果要绑定一个证书 要在哪里可以处理？

**Comment by RockyQu** [comment]
可以配置，在AppConfiguration里对外提供了一个okHttp的实例，可以写段证书相关的代码，加到这里

**Comment by RockyQu** [comment]
在APP Module→AppConfiguration类→applyOptions方法→okHttpConfiguration方法

**Comment by RockyQu** [comment]
builder.sslSocketFactory()好像要用到sslSocketFactory这个方法，具体我也没弄过，你得上网查查

**Comment by Puppy-Love** [comment]
多谢大佬 我去试试

**Comment by RockyQu** [comment]
@Puppy-Love 最近看了下关于Https证书的，分几种情况，可以忽略所有证书，证书单向验证，证书双向验证，还有些证书的类型也不同，所以可能不同的情况会出现不同配置需求，要是写在架构部分不好适应不同环境的App，已经对外提供了Okhttp，实际情况下还是自己配置下比较好些~在http.ssl包下我只加了个信任所有证书的代码
