### ISSUE TITLE
怎么通过AppComponent获取DaoSession实例

### ISSUE THREAD

**Issue by FireDream** [DesignQu/Project-Frame-MVP#4]

**Comment by RockyQu** [comment]
不能获取，因为注入模块在框架的Common底层部分，比如你在APP Module使用greendao，DaoSession这个文件是自动生成的，无法完全的封装到框架里，所经这部份得自己写，之前用时我也遇到过，我想把数据库完全放到框架里，好像不行。。。

**Comment by RockyQu** [comment]
你要还是想通过注入方法获取DaoSession，可以在APP Module再写个Component，这个Component继承AppComponent，在你新写的Component里取DaoSession，要不只能换个数据库框架了。。。。。

**Comment by RockyQu** [comment]
像以前用的xUtils，现在的Realm这类应该可以完全封装到框架里

**Comment by FireDream** [comment]
嗯，因为我在项目Features里看到里这条 “数据库模块 选择适用于Android的GreenDAO框架，通过AppComponent获取DaoSession实例”，那这个框架正确获取DaoSession实例的方式是什么呢？

**Comment by RockyQu** [comment]
就是在APP Module再写个Component，这个Component继承AppComponent，然后在你自己写的Application里注入一下，就行了

**Comment by RockyQu** [comment]
你要看一下dagger2的使用方法

**Comment by FireDream** [comment]
好的  我去看下 谢谢大神

**Comment by RockyQu** [comment]
这个框架的核心是https://github.com/JessYanCoding
这位写的，你也可以问问他

**Comment by FireDream** [comment]
嗯嗯，这个我也在看，大神能不能把写点操作数据库的代码上传一下

**Comment by RockyQu** [comment]
行，有时间我写写

**Comment by RockyQu** [comment]
@FireDream DaoSession的注入我在APP Module里写了一下，代码已上传了
