### ISSUE TITLE
ParameterInterceptor 的第63行报错

### ISSUE THREAD

**Issue by JingleDingDang** [DesignQu/Project-Frame-MVP#5]
接口形式
``` java
@POST("server")
@Streaming
Call<ResponseEntity<CsResponse>> startup(@Body CsRequest request);

```
然后报转换错误
java.lang.ClassCastException: okhttp3.RequestBody$1 cannot be cast to okhttp3.FormBody
建议添加不同类型的兼容。

**Comment by RockyQu** [comment]
谢谢，稍后修改，你可以暂时在配置类里先把ParameterInterceptor这个拦截器注掉

**Comment by JingleDingDang** [comment]
已经注释了，回复的好快，非常感谢提供这个好用的框架:wink:

**Comment by RockyQu** [comment]
修改好了
