### ISSUE TITLE
关于下载模块的建议

### ISSUE THREAD

**Issue by Redoteam** [DesignQu/Project-Frame-MVP#7]
1.首先感谢作者的辛苦付出，star和watch已点
2.希望下载模块能提供取消功能
3.同时本人自己也写了个取消功能，希望楼主不吝赐教（本人初级阶段）。
### 
public class DownloadCoreCache {

    private static Map<String,DownloadCore> downloadCoreMap = new HashMap<>();

    private static DownloadCoreCache downloadCoreCache;

    private DownloadCoreCache(){}

    public static DownloadCoreCache getInstall(){
        if(downloadCoreCache == null){
            downloadCoreCache = new DownloadCoreCache();
        }
        return downloadCoreCache;
    }

    /***
     * @param id : 任务id
     * @param downloadCore
     */
    public void put(String id,DownloadCore downloadCore){
        synchronized (downloadCoreMap){
            downloadCoreMap.put(id,downloadCore);
        }
    }

    public DownloadCore get(String id){
        synchronized (downloadCoreMap){
            return downloadCoreMap.get(id);
        }
    }

    public void remove(String id){
        synchronized (downloadCoreMap){
            downloadCoreMap.remove(id);
        }
    }

    public void clearAll(){
        synchronized (downloadCoreMap){
            downloadCoreMap.clear();
        }
    }
}
### 
 public static CoreExecute init(Application application, DownloadRequest request, DownloadListener listener) {
        DownloadCore downloadCore = new DownloadCore(application, request, listener);
        DownloadCoreCache.getInstall().put(request.getId(),downloadCore);
        return downloadCore;
    }

    public static void cancle(String id){
        DownloadCoreCache.getInstall().get(id).cancle();
    }
### @Override
    public void cancle() {
        isCancle = true;
    }
###  while ((len = is.read(buf)) != -1) {
                        fos.write(buf, 0, len);
                        sum += len;

                        // Downloading
                        if (downloadListener != null) {
                            downloadListener.onProgress(sum, total);
                        }
                        if(isCancle){
                            break;
                        }
                    }
### 因为之前在网上看到资料说，当call执行enqueue()方法后是无法取消的

# 如有冒犯之处，还请海涵，谢谢

**Comment by RockyQu** [comment]
谢谢你的建议，最近项目用到了，所以前几天刚加上一个基础版的，有时间我还要继续完善，白天比较忙，未来会加入你说的这些和多任务下载
